[[jobs]]
name = "Depletion"
time = [0, 240]
ch = [1, 512]
bc = "all"
target = [
  {region = ["chr1", "0", "248956422"], action= "unblock"},
  {region = ["chr11", "0", "135086622"], action = "unblock"},
  {region = ["chr5", "0", "181538259"], action = "unblock"},
  {region = ["chr2", "0", "242193529"], action = "unblock"},
  {region = ["chr12", "0", "133275309"], action = "unblock"},
  {region = "miss", action="stop_receiving"},
  {region = "unmapped", action="wait"},
]